### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SquidDev** [SquidDev/urn#1]
## Optimisations
- [x] Strip unused symbols
- [x] Constant propagation
- [x] Function inlining
- [x] Inline Lua operators
- [x] Convert tail recursive functions to loops
- [x] Don't emit native stuff when not needed

## Stdlib/syntax
- [x] Pattern maching
- [ ] Import with `require` instead.
- [x] Keys `:foo` for instance
- [x] Variadic arguments in the middle (`(lambda (foo &bar baz) ...)`).
- [ ] Metatables on `symbol`, `number` and `string`. Can we handle `true`, `false` and `nil` symbols "intelligently" too?

## Core
- [x] Statically bind symbols: hygenic macros
- [x] `unquote` in top level to "escape" compiler?
- [x] Variable metadata (export, documentation, etc...)

## Other
- [x] Documentation generation
- [ ] Typing
- [x] Deterministic compilation
- [x] Line mappings

**Comment by demhydraz** [comment]
You're not very good at this roadmap thing.

**Comment by demhydraz** [comment]
You've gotten good at this roadmap thing :smile:

**Comment by SquidDev** [comment]
I'm closing this in favour of the GitLab issue. Though most of the stuff on this list has either been done or is no longer relevant.
